spring:
  application:
    name: kudava

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/kudava}
  jpa:
    hibernate:
      ddl-auto: update
      defer-datasource-initialization: true

api:
  analysis:
    url: ${ANALYSIS_API:http://localhost:5050}